export type WorkCategory = "Websites" | "Apps" | "Agents";

export type Project = {
  slug: string;
  title: string;
  category: WorkCategory;
  outcome: string; // one-liner
  timeline: string;
  stack: string;
  result: string;
  thumbnail: string; // image or poster
  video?: string; // optional video src
  images: string[]; // 3-5 images
  metric?: string; // e.g., "Bounce ↓28%"
  industry?: string;
  year?: string;
  type?: string; // Mobile Apps, Web Apps, Websites, Auto Replies, AI Agents
};

// Helper to slugify titles (kept inline here if needed elsewhere later)
export const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");

export const projects: Project[] = [
  {
    slug: slugify("Convention Center Wayfinding"),
    title: "Convention Center Wayfinding",
    category: "Apps",
    outcome: "4× faster decisions with realtime indoor maps.",
    timeline: "10 weeks",
    stack: "Next.js, Mapbox, Firebase",
    result: "50% faster navigation, fewer support calls.",
    thumbnail: "/placeholders/cc-wayfinding/thumb.svg",
    metric: "Speed ↑4×",
    industry: "Events",
    year: "2024",
    type: "Mobile Apps",
    images: [
      "/placeholders/cc-wayfinding/1.svg",
      "/placeholders/cc-wayfinding/2.svg",
      "/placeholders/cc-wayfinding/3.svg",
    ],
  },
  {
    slug: slugify("Barndominium Configurator"),
    title: "Barndominium Configurator",
    category: "Apps",
    outcome: "Bookings up 32% with visual build configurator.",
    timeline: "8 weeks",
    stack: "Next.js, Three.js, Stripe",
    result: "Higher conversion and shorter sales cycles.",
    thumbnail: "/placeholders/barndo-config/thumb.svg",
    metric: "Bookings ↑32%",
    industry: "E-commerce",
    year: "2023",
    type: "Web Apps",
    images: [
      "/placeholders/barndo-config/1.svg",
      "/placeholders/barndo-config/2.svg",
      "/placeholders/barndo-config/3.svg",
    ],
  },
  {
    slug: slugify("Social Butterflie"),
    title: "Social Butterflie",
    category: "Agents",
    outcome: "Content creation time cut 70% with AI agent.",
    timeline: "6 weeks",
    stack: "Next.js, OpenAI, Supabase",
    result: "Consistent posts with brand-safe tone.",
    thumbnail: "/placeholders/social-butterflie/thumb.svg",
    metric: "Time ↓70%",
    industry: "SaaS",
    year: "2024",
    type: "AI Agents",
    images: [
      "/placeholders/social-butterflie/1.svg",
      "/placeholders/social-butterflie/2.svg",
      "/placeholders/social-butterflie/3.svg",
    ],
  },
  {
    slug: slugify("Campus POI"),
    title: "Campus POI",
    category: "Apps",
    outcome: "Campus engagement up 45% with AR explorer.",
    timeline: "7 weeks",
    stack: "Expo, Next.js, Firebase",
    result: "Better campus tours and engagement.",
    thumbnail: "/placeholders/campus-poi/thumb.svg",
    metric: "Engagement ↑45%",
    industry: "Education",
    year: "2023",
    type: "Mobile Apps",
    images: [
      "/placeholders/campus-poi/1.svg",
      "/placeholders/campus-poi/2.svg",
      "/placeholders/campus-poi/3.svg",
    ],
  },
  {
    slug: slugify("Builder Portal"),
    title: "Builder Portal",
    category: "Websites",
    outcome: "Support tickets down 60% with self-serve portal.",
    timeline: "5 weeks",
    stack: "Next.js, Auth.js, Postgres",
    result: "Reduced support tickets and faster onboarding.",
    thumbnail: "/placeholders/builder-portal/thumb.svg",
    metric: "Tickets ↓60%",
    industry: "SaaS",
    year: "2023",
    type: "Websites",
    images: [
      "/placeholders/builder-portal/1.svg",
      "/placeholders/builder-portal/2.svg",
      "/placeholders/builder-portal/3.svg",
    ],
  },
  {
    slug: slugify("Med Spa CMS"),
    title: "Med Spa CMS",
    category: "Websites",
    outcome: "Bookings up 38% with high-converting CMS pages.",
    timeline: "4 weeks",
    stack: "Next.js, Sanity, Vercel",
    result: "More bookings with less friction.",
    thumbnail: "/placeholders/med-spa-cms/thumb.svg",
    metric: "Bookings ↑38%",
    industry: "Healthcare",
    year: "2023",
    type: "Websites",
    images: [
      "/placeholders/med-spa-cms/1.svg",
      "/placeholders/med-spa-cms/2.svg",
      "/placeholders/med-spa-cms/3.svg",
    ],
  },
  // 2024 Projects
  {
    slug: slugify("E-commerce Platform"),
    title: "E-commerce Platform", 
    category: "Websites",
    outcome: "300% conversion increase with optimized checkout flow.",
    timeline: "8 weeks",
    stack: "Next.js, Stripe, Shopify",
    result: "Seamless shopping experience with 1-click checkout.",
    thumbnail: "/placeholders/ecommerce-platform/thumb.svg",
    metric: "Conversion ↑300%",
    industry: "E-commerce",
    year: "2024",
    type: "Websites",
    images: [
      "/placeholders/ecommerce-platform/1.svg",
      "/placeholders/ecommerce-platform/2.svg", 
      "/placeholders/ecommerce-platform/3.svg",
    ],
  },
  {
    slug: slugify("FinTech Dashboard"),
    title: "FinTech Dashboard",
    category: "Apps",
    outcome: "Real-time portfolio tracking with AI insights.",
    timeline: "12 weeks", 
    stack: "React Native, WebSocket, AI",
    result: "Users report 90% faster investment decisions.",
    thumbnail: "/placeholders/fintech-dashboard/thumb.svg",
    metric: "Speed ↑90%",
    industry: "Finance",
    year: "2024",
    type: "Mobile Apps",
    images: [
      "/placeholders/fintech-dashboard/1.svg",
      "/placeholders/fintech-dashboard/2.svg",
      "/placeholders/fintech-dashboard/3.svg", 
    ],
  },
  {
    slug: slugify("Entertainment Hub"),
    title: "Entertainment Hub",
    category: "Apps",
    outcome: "Streaming engagement up 150% with personalized UI.",
    timeline: "10 weeks",
    stack: "React Native, Firebase, ML",
    result: "Smart recommendations and seamless streaming.",
    thumbnail: "/placeholders/entertainment-hub/thumb.svg", 
    metric: "Engagement ↑150%",
    industry: "Entertainment",
    year: "2024",
    type: "Mobile Apps",
    images: [
      "/placeholders/entertainment-hub/1.svg",
      "/placeholders/entertainment-hub/2.svg",
      "/placeholders/entertainment-hub/3.svg",
    ],
  },
  {
    slug: slugify("Learning Management System"),
    title: "Learning Management System",
    category: "Websites", 
    outcome: "Student completion rates improved by 85%.",
    timeline: "14 weeks",
    stack: "Next.js, PostgreSQL, WebRTC",
    result: "Interactive learning with video calls and real-time collaboration.",
    thumbnail: "/placeholders/lms/thumb.svg",
    metric: "Completion ↑85%",
    industry: "Education",
    year: "2024",
    type: "Web Apps",
    images: [
      "/placeholders/lms/1.svg",
      "/placeholders/lms/2.svg",
      "/placeholders/lms/3.svg",
    ],
  },
  // 2025 Projects
  {
    slug: slugify("AI Customer Support Agent"),
    title: "AI Customer Support Agent",
    category: "Agents",
    outcome: "24/7 support with 95% resolution rate.",
    timeline: "6 weeks",
    stack: "OpenAI GPT-4, Next.js, WebSocket",
    result: "Handles 1000+ queries daily with human-like responses.",
    thumbnail: "/placeholders/ai-support-agent/thumb.svg", 
    metric: "Resolution ↑95%",
    industry: "SaaS",
    year: "2025",
    type: "AI Agents",
    images: [
      "/placeholders/ai-support-agent/1.svg",
      "/placeholders/ai-support-agent/2.svg",
      "/placeholders/ai-support-agent/3.svg",
    ],
  },
  {
    slug: slugify("Healthcare Diagnostic Agent"),
    title: "Healthcare Diagnostic Agent", 
    category: "Agents",
    outcome: "Initial screening accuracy improved by 40%.",
    timeline: "16 weeks",
    stack: "OpenAI, Medical APIs, HIPAA",
    result: "Pre-screening patients and scheduling with 99% HIPAA compliance.",
    thumbnail: "/placeholders/health-diagnostic-agent/thumb.svg",
    metric: "Accuracy ↑40%",
    industry: "Healthcare", 
    year: "2025",
    type: "AI Agents",
    images: [
      "/placeholders/health-diagnostic-agent/1.svg",
      "/placeholders/health-diagnostic-agent/2.svg",
      "/placeholders/health-diagnostic-agent/3.svg",
    ],
  },
  {
    slug: slugify("Smart Auto Reply System"),
    title: "Smart Auto Reply System",
    category: "Apps",
    outcome: "Email response time reduced by 80%.", 
    timeline: "4 weeks",
    stack: "OpenAI, IMAP, Next.js",
    result: "Intelligent email categorization and automatic responses.",
    thumbnail: "/placeholders/auto-reply/thumb.svg",
    metric: "Response ↓80%",
    industry: "SaaS",
    year: "2025",
    type: "Auto Replies", 
    images: [
      "/placeholders/auto-reply/1.svg",
      "/placeholders/auto-reply/2.svg",
      "/placeholders/auto-reply/3.svg",
    ],
  },
  {
    slug: slugify("Banking Web Portal"),
    title: "Banking Web Portal",
    category: "Websites",
    outcome: "Account management efficiency increased 200%.",
    timeline: "20 weeks", 
    stack: "Next.js, Banking APIs, 2FA",
    result: "Secure portal with biometric auth and real-time transactions.",
    thumbnail: "/placeholders/banking-portal/thumb.svg",
    metric: "Efficiency ↑200%",
    industry: "Finance",
    year: "2025",
    type: "Web Apps",
    images: [
      "/placeholders/banking-portal/1.svg", 
      "/placeholders/banking-portal/2.svg",
      "/placeholders/banking-portal/3.svg",
    ],
  },
];
